version: 4.0.0-{branch}-ci-{build}

branches:
  only:
  - default

#shallow clone does not work when subrepos are involved!
#shallow_clone: true

environment:
  BB_AUTH_STRING:
    secure: IyP2dNdsGf1iao8XFeiu7R8Fk+ZWBYd4vJlHZv1XcLy6KWcwSxLtjHZsTUSoiV/e

  matrix:
#    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
#      CMAKE_GENERATOR: 'Unix Makefiles'
#      CMAKE_CONFIGURATION: Release
#      CMAKE_PLATFORM: x86
#      CMAKE_ARCH_FLAGS: -m32
#      COMPILER_ID: gcc5
#      configuration: Release
#      platform: x86
#
#    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
#      CMAKE_GENERATOR: 'Unix Makefiles'
#      CMAKE_CONFIGURATION: Release
#      CMAKE_PLATFORM: x64
#      CMAKE_ARCH_FLAGS: -m64
#      COMPILER_ID: gcc5
#      configuration: Release
#      platform: x64
#
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: 'Visual Studio 10 2010'
      CMAKE_ARCHITECTURE: Win32
      CMAKE_CONFIGURATION: Release
      CMAKE_PLATFORM: x86
      COMPILER_ID: msvc10
      configuration: Release
      platform: x86

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: 'Visual Studio 10 2010'
      CMAKE_ARCHITECTURE: x64
      CMAKE_CONFIGURATION: Release
      CMAKE_PLATFORM: x64
      COMPILER_ID: msvc10
      configuration: Release
      platform: x64

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: 'Visual Studio 14 2015'
      CMAKE_ARCHITECTURE: Win32
      CMAKE_CONFIGURATION: Release
      CMAKE_PLATFORM: x86
      COMPILER_ID: msvc14
      configuration: Release
      platform: x86

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: 'Visual Studio 14 2015'
      CMAKE_ARCHITECTURE: x64
      CMAKE_CONFIGURATION: Release
      CMAKE_PLATFORM: x64
      COMPILER_ID: msvc14
      configuration: Release
      platform: x64

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: 'Visual Studio 15 2017'
      CMAKE_ARCHITECTURE: Win32
      CMAKE_CONFIGURATION: Release
      CMAKE_PLATFORM: x86
      COMPILER_ID: msvc15
      configuration: Release
      platform: x86

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: 'Visual Studio 15 2017'
      CMAKE_ARCHITECTURE: x64
      CMAKE_CONFIGURATION: Release
      CMAKE_PLATFORM: x64
      COMPILER_ID: msvc15
      configuration: Release
      platform: x64

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019 Preview
      CMAKE_GENERATOR: 'Visual Studio 16 2019'
      CMAKE_ARCHITECTURE: Win32
      CMAKE_CONFIGURATION: Release
      CMAKE_PLATFORM: x86
      COMPILER_ID: msvc16
      configuration: Release
      platform: x86

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019 Preview
      CMAKE_GENERATOR: 'Visual Studio 16 2019'
      CMAKE_ARCHITECTURE: x64
      CMAKE_CONFIGURATION: Release
      CMAKE_PLATFORM: x64
      COMPILER_ID: msvc16
      configuration: Release
      platform: x64

install:
  - sh: |
      if [ "$CMAKE_PLATFORM" == "x86" ]
      then
        sudo apt-get install freeglut3-dev:i386 -y
      elif [ "$CMAKE_PLATFORM" == "x64" ]
      then
        sudo apt-get install freeglut3-dev -y
      fi
      sudo apt-get install doxygen -y
      sudo apt-get install gcc-multilib -y
      sudo apt-get install g++-multilib -y
  - cmd: |
      set PATH=%APPVEYOR_BUILD_FOLDER%\downloads\doxygen-1.8.14;%APPVEYOR_BUILD_FOLDER%\downloads\cmake-3.14.5-win64-x64\bin;%PATH%

before_build:
  - cmd: |
      set BUILD_SOURCE_ARCHIVE=%APPVEYOR_PROJECT_NAME%-4.0.0-src.zip
      7z a -tzip %BUILD_SOURCE_ARCHIVE% %APPVEYOR_BUILD_FOLDER%
      appveyor PushArtifact %BUILD_SOURCE_ARCHIVE%
      mkdir %APPVEYOR_BUILD_FOLDER%\downloads
      set DOWNLOAD_FILE_DOXYGEN=doxygen-1.8.14.windows.x64.bin.zip
      set DOWNLOAD_ADDRESS_DOXYGEN=https://sourceforge.net/projects/doxygen/files/rel-1.8.14/%DOWNLOAD_FILE_DOXYGEN%
      curl -fsSL -G -o "%DOWNLOAD_FILE_DOXYGEN%" "%DOWNLOAD_ADDRESS_DOXYGEN%"
      7z x %DOWNLOAD_FILE_DOXYGEN% -o%APPVEYOR_BUILD_FOLDER%\downloads\doxygen-1.8.14
      doxygen --version
      set DOWNLOAD_FILE_SUPERGLU=superglu-1.3.0-%COMPILER_ID%-%CMAKE_PLATFORM%-%CMAKE_CONFIGURATION%.zip
      set DOWNLOAD_ADDRESS_SUPERGLU=https://ci.appveyor.com/api/projects/%APPVEYOR_ACCOUNT_NAME%/superglu/artifacts/%DOWNLOAD_FILE_SUPERGLU%
      curl -fsSL -G -o "%DOWNLOAD_FILE_SUPERGLU%" "%DOWNLOAD_ADDRESS_SUPERGLU%" --data-urlencode "branch=default" --data-urlencode "job=Environment: APPVEYOR_BUILD_WORKER_IMAGE=%APPVEYOR_BUILD_WORKER_IMAGE%, CMAKE_GENERATOR=%CMAKE_GENERATOR%, CMAKE_CONFIGURATION=%CMAKE_CONFIGURATION%, CMAKE_PLATFORM=%CMAKE_PLATFORM%, COMPILER_ID=%COMPILER_ID%, configuration=%CMAKE_CONFIGURATION%, platform=%CMAKE_PLATFORM%"
      7z x %DOWNLOAD_FILE_SUPERGLU% -o%APPVEYOR_BUILD_FOLDER%\downloads
      set DOWNLOAD_FILE_CMAKE=cmake-3.14.5-win64-x64.zip
      set DOWNLOAD_ADDRESS_CMAKE=https://github.com/Kitware/CMake/releases/download/v3.14.5/%DOWNLOAD_FILE_CMAKE%
      curl -fsSL -G -o "%DOWNLOAD_FILE_CMAKE%" "%DOWNLOAD_ADDRESS_CMAKE%"
      7z x %DOWNLOAD_FILE_CMAKE% -o%APPVEYOR_BUILD_FOLDER%\downloads
      cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" -A %CMAKE_ARCHITECTURE% -DCMAKE_CONFIGURATION_TYPES=%CMAKE_CONFIGURATION% -DCMAKE_TRY_COMPILE_CONFIGURATION=%CMAKE_CONFIGURATION% -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\Coin3D -DCMAKE_PREFIX_PATH=%APPVEYOR_BUILD_FOLDER%\downloads\Coin3D -DBOOST_ROOT=C:\Libraries\boost_1_69_0
  - sh: |
      BUILD_SOURCE_ARCHIVE=$APPVEYOR_PROJECT_NAME-4.0.0-src.tar.gz
      tar -czvf $BUILD_SOURCE_ARCHIVE $APPVEYOR_BUILD_FOLDER/*
      appveyor PushArtifact $BUILD_SOURCE_ARCHIVE
      mkdir $APPVEYOR_BUILD_FOLDER/downloads
      export CFLAGS=$CMAKE_ARCH_FLAGS
      export CXXFLAGS=$CMAKE_ARCH_FLAGS
      cmake -H. -Bbuild -G "$CMAKE_GENERATOR" -A $CMAKE_ARCHITECTURE -DCMAKE_BUILD_TYPE=$CMAKE_CONFIGURATION -DCMAKE_POSITION_INDEPENDENT_CODE=true -DCMAKE_INSTALL_PREFIX=$APPVEYOR_BUILD_FOLDER/Coin3D -DCMAKE_PREFIX_PATH=$APPVEYOR_BUILD_FOLDER/downloads/Coin3D

build_script:
  - cmd: |
      set BUILD_TOOL_OPTIONS=/nologo /verbosity:minimal /maxcpucount
      cmake --build build --target ALL_BUILD --config %CMAKE_CONFIGURATION% -- %BUILD_TOOL_OPTIONS%
      cmake --build build --target INSTALL   --config %CMAKE_CONFIGURATION% -- %BUILD_TOOL_OPTIONS%
  - sh: |
      BUILD_TOOL_OPTIONS=-j4
      cmake --build build --target all       --config $CMAKE_CONFIGURATION -- $BUILD_TOOL_OPTIONS
      cmake --build build --target install   --config $CMAKE_CONFIGURATION -- $BUILD_TOOL_OPTIONS

after_build:
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%
      set BUILD_ARCHIVE=%APPVEYOR_PROJECT_NAME%-4.0.0-%COMPILER_ID%-%CMAKE_PLATFORM%-%CMAKE_CONFIGURATION%.zip
      7z a -tzip %BUILD_ARCHIVE% Coin3D
      appveyor PushArtifact %BUILD_ARCHIVE%
  - sh: |
      cd $APPVEYOR_BUILD_FOLDER
      BUILD_ARCHIVE=$APPVEYOR_PROJECT_NAME-4.0.0-$COMPILER_ID-$CMAKE_PLATFORM-$CMAKE_CONFIGURATION.tar.gz
      tar -czvf $BUILD_ARCHIVE Coin3D/*
      appveyor PushArtifact $BUILD_ARCHIVE

test_script:
  - cmd: |
      cd build
      ctest -C %CMAKE_CONFIGURATION% -VV
  - sh: |
      cd build
      ctest -C $CMAKE_CONFIGURATION -VV

on_success:
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%
      curl --user %BB_AUTH_STRING% https://api.bitbucket.org/2.0/repositories/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%/downloads --form files=@%BUILD_ARCHIVE%
      curl --user %BB_AUTH_STRING% https://api.bitbucket.org/2.0/repositories/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%/downloads --form files=@%BUILD_SOURCE_ARCHIVE%
  - sh: |
      cd $APPVEYOR_BUILD_FOLDER
      curl --user $BB_AUTH_STRING  https://api.bitbucket.org/2.0/repositories/$APPVEYOR_ACCOUNT_NAME/$APPVEYOR_PROJECT_SLUG/downloads   --form files=\@$BUILD_ARCHIVE
      curl --user $BB_AUTH_STRING  https://api.bitbucket.org/2.0/repositories/$APPVEYOR_ACCOUNT_NAME/$APPVEYOR_PROJECT_SLUG/downloads   --form files=\@$BUILD_SOURCE_ARCHIVE

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
      - coin-support@coin3d.org
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
